# Generated by Django 4.2.23 on 2025-07-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='serie',
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(default='Curso Genérico', max_length=100),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.curso'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(default='Disciplina Genérica', max_length=60),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.disciplina'),
        ),
        migrations.AddField(
            model_name='professor',
            name='emailProf',
            field=models.EmailField(blank=True, default=None, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_turma',
            field=models.CharField(default='2025', max_length=50),
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.professor'),
        ),
    ]
