# Generated by Django 4.2.23 on 2025-07-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_curso_tecnico_remove_disciplina_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='data_frequencia',
            field=models.DateField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.turma'),
        ),
    ]
